resolver: lts-9.21
compiler: ghcjs-0.2.1.9009021_ghc-8.0.2
compiler-check: match-exact
setup-info:
 ghcjs:
   source:
     ghcjs-0.2.1.9009021_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/develop/ghcjs-0.2.1.9009021.1.tar.gz
        sha1: db8cd3252e47dbef3db7d1cf0d6d997e8d029f84

packages:
- '.'
- location:
    git: git@github.com:reflex-frp/reflex.git
    commit: d78ba4318c425ca9b942dc387d7c5c7ab2d2e095
  extra-dep: true
- location:
    git: git@github.com:reflex-frp/reflex-dom.git
    commit: ff9351a1859a07f8f3892d6381e9d5d0cd500d5d
  extra-dep: true
# extra-deps:
# - ghcjs-dom-0.2.4.0
# - ref-tf-0.4.0.1
# - data-default-0.6.0
# - data-default-instances-base-0.1.0.1
#
# - zenc-0.1.1

extra-deps:
  - ref-tf-0.4.0.1
  - prim-uniq-0.1.0.1
  - dependent-sum-template-0.0.0.6
  - ghcjs-dom-0.2.4.0
  - zenc-0.1.1
  - haskell-src-exts-1.17.1
  - haskell-src-meta-0.6.0.14


allow-newer: true