resolver: lts-11.20
compiler: ghcjs-8.2.0.1001120_ghc-8.2.2
compiler-check: match-exact


packages:
- '.'

# extra-deps:
# - ghcjs-dom-0.2.4.0
# - ref-tf-0.4.0.1
# - data-default-0.6.0
# - data-default-instances-base-0.1.0.1
#
# - zenc-0.1.1

# extra-deps:
#
#   - prim-uniq-0.1.0.1
#   - dependent-sum-template-0.0.0.6
#
#
#   - haskell-src-exts-1.17.1
#   - haskell-src-meta-0.6.0.14

extra-deps:
  - ghcjs-dom-0.9.2.0
  - ghcjs-dom-jsffi-0.9.2.0
  - jsaddle-0.9.5.0
  - ref-tf-0.4.0.1
  - zenc-0.1.1
  - /code/ghcjs/ghcjs-base
  - git: git@github.com:reflex-frp/reflex.git
    commit: 39d9392b191ec85052eb8839f6c9f207f9e21885
  - git: git@github.com:reflex-frp/reflex-dom.git
    commit: 4a65735dab7cc23962621a536fef4aaf983b3881
    subdirs:
      - reflex-dom
      - reflex-dom-core
allow-newer: true